import 'package:flutter_test/flutter_test.dart';
import 'package:flutter/material.dart';

import 'package:timeline_xp/timeline_xp.dart';

void main() {
  const project = {
    'prj_id': '254354-245254-245245',
    'prj_name': 'Swiip',
    'prj_status': 'active',
    'prj_startdate': "2024-08-01",
    'prj_enddate': "2024-09-30",
  };

  const List<dynamic> elements = [
    {
      'date': "2024-07-22",
      'capacityLevelMax': 10,
      'capacityLevel': 8,
      'workLoadLevel': 6,
      'completedLevel': 4,
      'myWorkLoadLevel': 4,
      'myCompletedLevel': 1,
      'activityTotal': 4,
      'activityCompleted': 3,
      'delivrableTotal': 4,
      'delivrableCompleted': 2,
      'taskTotal': 1,
      'task': 3,
      'alertLevel': 1,
      'hustle': 1
    },
    {
      'date': "2024-08-01",
      'capacityLevelMax': 10,
      'capacityLevel': 8,
      'workLoadLevel': 6,
      'completedLevel': 4,
      'myWorkLoadLevel': 4,
      'myCompletedLevel': 1,
      'activityTotal': 4,
      'activityCompleted': 3,
      'delivrableTotal': 4,
      'delivrableCompleted': 2,
      'taskTotal': 1,
      'task': 3,
      'alertLevel': 1,
      'hustle': 1
    },
    {
      'date': "2024-08-02",
      'capacityLevelMax': 10,
      'capacityLevel': 10,
      'workLoadLevel': 6,
      'completedLevel': 4,
      'myWorkLoadLevel': 3,
      'myCompletedLevel': 1,
      'activityTotal': 4,
      'activityCompleted': 3,
      'delivrableTotal': 4,
      'delivrableCompleted': 2,
      'taskTotal': 1,
      'task': 3,
      'alertLevel': 1,
      'hustle': 1
    },
    {
      'date': "2024-08-03",
      'capacityLevelMax': 10,
      'capacityLevel': 10,
      'workLoadLevel': 4,
      'completedLevel': 2,
      'myWorkLoadLevel': 3,
      'myCompletedLevel': 1,
      'activityTotal': 4,
      'activityCompleted': 3,
      'delivrableTotal': 4,
      'delivrableCompleted': 2,
      'taskTotal': 1,
      'task': 3,
      'alertLevel': 2,
      'hustle': 1
    },
    {
      'date': "2024-08-04",
      'capacityLevelMax': 10,
      'capacityLevel': 10,
      'workLoadLevel': 6,
      'completedLevel': 4,
      'myWorkLoadLevel': 6,
      'myCompletedLevel': 4,
      'activityTotal': 4,
      'activityCompleted': 3,
      'delivrableTotal': 4,
      'delivrableCompleted': 2,
      'taskTotal': 1,
      'task': 3,
      'alertLevel': 2,
      'hustle': 1
    },
    {
      'date': "2024-08-05",
      'capacityLevelMax': 10,
      'capacityLevel': 8,
      'workLoadLevel': 6,
      'completedLevel': 4,
      'myWorkLoadLevel': 4,
      'myCompletedLevel': 4,
      'activityTotal': 4,
      'activityCompleted': 3,
      'delivrableTotal': 4,
      'delivrableCompleted': 2,
      'taskTotal': 1,
      'task': 3,
      'alertLevel': 0,
      'hustle': 1
    },
    {
      'date': "2024-08-06",
      'capacityLevelMax': 0,
      'capacityLevel': 0,
      'workLoadLevel': 0,
      'completedLevel': 0,
      'myWorkLoadLevel': 0,
      'myCompletedLevel': 0,
      'activityTotal': 0,
      'activityCompleted': 0,
      'delivrableTotal': 0,
      'delivrableCompleted': 0,
      'taskTotal': 0,
      'task': 0,
      'alertLevel': 0,
      'hustle': 1
    },
    {
      'date': "2024-08-07",
      'capacityLevelMax': 0,
      'capacityLevel': 0,
      'workLoadLevel': 0,
      'completedLevel': 0,
      'myWorkLoadLevel': 0,
      'myCompletedLevel': 0,
      'activityTotal': 0,
      'activityCompleted': 0,
      'delivrableTotal': 0,
      'delivrableCompleted': 0,
      'taskTotal': 0,
      'task': 0,
      'alertLevel': 0,
      'hustle': 1
    },
    {
      'date': "2024-08-08",
      'capacityLevelMax': 10,
      'capacityLevel': 8,
      'workLoadLevel': 6,
      'completedLevel': 1,
      'myWorkLoadLevel': 0,
      'myCompletedLevel': 0,
      'activityTotal': 4,
      'activityCompleted': 3,
      'delivrableTotal': 4,
      'delivrableCompleted': 2,
      'taskTotal': 1,
      'task': 3,
      'alertLevel': 0,
      'hustle': 1
    },
    {
      'date': "2024-08-09",
      'capacityLevelMax': 10,
      'capacityLevel': 8,
      'workLoadLevel': 8,
      'completedLevel': 0,
      'myWorkLoadLevel': 0,
      'myCompletedLevel': 0,
      'activityTotal': 4,
      'activityCompleted': 3,
      'delivrableTotal': 4,
      'delivrableCompleted': 2,
      'taskTotal': 1,
      'task': 3,
      'alertLevel': 0,
      'hustle': 1
    },
    {
      'date': "2024-08-10",
      'capacityLevelMax': 10,
      'capacityLevel': 8,
      'workLoadLevel': 8,
      'completedLevel': 0,
      'myWorkLoadLevel': 0,
      'myCompletedLevel': 0,
      'activityTotal': 4,
      'activityCompleted': 3,
      'delivrableTotal': 4,
      'delivrableCompleted': 2,
      'taskTotal': 1,
      'task': 3,
      'alertLevel': 0,
      'hustle': 1
    },
    {
      'date': "2024-08-11",
      'capacityLevelMax': 10,
      'capacityLevel': 8,
      'workLoadLevel': 6,
      'completedLevel': 4,
      'myWorkLoadLevel': 0,
      'myCompletedLevel': 0,
      'activityTotal': 4,
      'activityCompleted': 3,
      'delivrableTotal': 4,
      'delivrableCompleted': 2,
      'taskTotal': 1,
      'task': 3,
      'alertLevel': 0,
      'hustle': 1
    },
    {
      'date': "2024-08-12",
      'capacityLevelMax': 10,
      'capacityLevel': 8,
      'workLoadLevel': 6,
      'completedLevel': 4,
      'myWorkLoadLevel': 0,
      'myCompletedLevel': 0,
      'activityTotal': 4,
      'activityCompleted': 3,
      'delivrableTotal': 4,
      'delivrableCompleted': 2,
      'taskTotal': 1,
      'task': 3,
      'alertLevel': 0,
      'hustle': 1
    },
    {
      'date': "2024-08-13",
      'capacityLevelMax': 10,
      'capacityLevel': 8,
      'workLoadLevel': 6,
      'completedLevel': 4,
      'myWorkLoadLevel': 0,
      'myCompletedLevel': 0,
      'activityTotal': 4,
      'activityCompleted': 3,
      'delivrableTotal': 4,
      'delivrableCompleted': 2,
      'taskTotal': 1,
      'task': 3,
      'alertLevel': 0,
      'hustle': 1
    },
    {
      'date': "2024-08-14",
      'capacityLevelMax': 10,
      'capacityLevel': 8,
      'workLoadLevel': 6,
      'completedLevel': 4,
      'myWorkLoadLevel': 0,
      'myCompletedLevel': 0,
      'activityTotal': 4,
      'activityCompleted': 3,
      'delivrableTotal': 4,
      'delivrableCompleted': 2,
      'taskTotal': 1,
      'task': 3,
      'alertLevel': 0,
      'hustle': 1
    },
    {
      'date': "2024-08-15",
      'capacityLevelMax': 10,
      'capacityLevel': 8,
      'workLoadLevel': 6,
      'completedLevel': 4,
      'myWorkLoadLevel': 0,
      'myCompletedLevel': 0,
      'activityTotal': 4,
      'activityCompleted': 3,
      'delivrableTotal': 4,
      'delivrableCompleted': 2,
      'taskTotal': 1,
      'task': 3,
      'alertLevel': 0,
      'hustle': 1
    },
    {
      'date': "2024-08-16",
      'capacityLevelMax': 10,
      'capacityLevel': 8,
      'workLoadLevel': 6,
      'completedLevel': 4,
      'myWorkLoadLevel': 0,
      'myCompletedLevel': 0,
      'activityTotal': 4,
      'activityCompleted': 3,
      'delivrableTotal': 4,
      'delivrableCompleted': 2,
      'taskTotal': 1,
      'task': 3,
      'alertLevel': 0,
      'hustle': 1
    },
    {
      'date': "2024-08-17",
      'capacityLevelMax': 10,
      'capacityLevel': 8,
      'workLoadLevel': 6,
      'completedLevel': 4,
      'myWorkLoadLevel': 0,
      'myCompletedLevel': 0,
      'activityTotal': 4,
      'activityCompleted': 3,
      'delivrableTotal': 4,
      'delivrableCompleted': 2,
      'taskTotal': 1,
      'task': 3,
      'alertLevel': 1,
      'hustle': 1
    },
    {
      'date': "2024-08-18",
      'capacityLevelMax': 10,
      'capacityLevel': 8,
      'workLoadLevel': 6,
      'completedLevel': 4,
      'myWorkLoadLevel': 0,
      'myCompletedLevel': 0,
      'activityTotal': 4,
      'activityCompleted': 3,
      'delivrableTotal': 4,
      'delivrableCompleted': 2,
      'taskTotal': 1,
      'task': 3,
      'alertLevel': 0,
      'hustle': 1
    },
    {
      'date': "2024-08-19",
      'capacityLevelMax': 10,
      'capacityLevel': 8,
      'workLoadLevel': 6,
      'completedLevel': 4,
      'myWorkLoadLevel': 0,
      'myCompletedLevel': 0,
      'activityTotal': 4,
      'activityCompleted': 3,
      'delivrableTotal': 4,
      'delivrableCompleted': 2,
      'taskTotal': 1,
      'task': 3,
      'alertLevel': 0,
      'hustle': 1
    },
    {
      'date': "2024-08-20",
      'capacityLevelMax': 10,
      'capacityLevel': 8,
      'workLoadLevel': 6,
      'completedLevel': 4,
      'myWorkLoadLevel': 0,
      'myCompletedLevel': 0,
      'activityTotal': 4,
      'activityCompleted': 3,
      'delivrableTotal': 4,
      'delivrableCompleted': 2,
      'taskTotal': 1,
      'task': 3,
      'alertLevel': 0,
      'hustle': 1
    },
    {
      'date': "2024-08-21",
      'capacityLevelMax': 10,
      'capacityLevel': 8,
      'workLoadLevel': 6,
      'completedLevel': 4,
      'myWorkLoadLevel': 0,
      'myCompletedLevel': 0,
      'activityTotal': 4,
      'activityCompleted': 3,
      'delivrableTotal': 4,
      'delivrableCompleted': 2,
      'taskTotal': 1,
      'task': 3,
      'alertLevel': 0,
      'hustle': 1
    },
    {
      'date': "2024-08-22",
      'capacityLevelMax': 10,
      'capacityLevel': 8,
      'workLoadLevel': 6,
      'completedLevel': 4,
      'myWorkLoadLevel': 0,
      'myCompletedLevel': 0,
      'activityTotal': 4,
      'activityCompleted': 3,
      'delivrableTotal': 4,
      'delivrableCompleted': 2,
      'taskTotal': 1,
      'task': 3,
      'alertLevel': 0,
      'hustle': 1
    },
    {
      'date': "2024-08-23",
      'capacityLevelMax': 10,
      'capacityLevel': 8,
      'workLoadLevel': 6,
      'completedLevel': 4,
      'myWorkLoadLevel': 0,
      'myCompletedLevel': 0,
      'activityTotal': 4,
      'activityCompleted': 3,
      'delivrableTotal': 4,
      'delivrableCompleted': 2,
      'taskTotal': 1,
      'task': 3,
      'alertLevel': 0,
      'hustle': 1
    },
    {
      'date': "2024-08-24",
      'capacityLevelMax': 10,
      'capacityLevel': 8,
      'workLoadLevel': 6,
      'completedLevel': 4,
      'myWorkLoadLevel': 0,
      'myCompletedLevel': 0,
      'activityTotal': 4,
      'activityCompleted': 3,
      'delivrableTotal': 4,
      'delivrableCompleted': 2,
      'taskTotal': 1,
      'task': 3,
      'alertLevel': 0,
      'hustle': 1
    },
    {
      'date': "2024-08-25",
      'capacityLevelMax': 10,
      'capacityLevel': 8,
      'workLoadLevel': 6,
      'completedLevel': 4,
      'myWorkLoadLevel': 0,
      'myCompletedLevel': 0,
      'activityTotal': 4,
      'activityCompleted': 3,
      'delivrableTotal': 4,
      'delivrableCompleted': 2,
      'taskTotal': 1,
      'task': 3,
      'alertLevel': 0,
      'hustle': 1
    },
    {
      'date': "2024-08-26",
      'capacityLevelMax': 10,
      'capacityLevel': 8,
      'workLoadLevel': 6,
      'completedLevel': 4,
      'myWorkLoadLevel': 0,
      'myCompletedLevel': 0,
      'activityTotal': 4,
      'activityCompleted': 3,
      'delivrableTotal': 4,
      'delivrableCompleted': 2,
      'taskTotal': 1,
      'task': 3,
      'alertLevel': 0,
      'hustle': 1
    },
    {
      'date': "2024-08-27",
      'capacityLevelMax': 10,
      'capacityLevel': 8,
      'workLoadLevel': 6,
      'completedLevel': 4,
      'myWorkLoadLevel': 0,
      'myCompletedLevel': 0,
      'activityTotal': 4,
      'activityCompleted': 3,
      'delivrableTotal': 4,
      'delivrableCompleted': 2,
      'taskTotal': 1,
      'task': 3,
      'alertLevel': 0,
      'hustle': 1
    },
    {
      'date': "2024-08-28",
      'capacityLevelMax': 10,
      'capacityLevel': 8,
      'workLoadLevel': 6,
      'completedLevel': 4,
      'myWorkLoadLevel': 0,
      'myCompletedLevel': 0,
      'activityTotal': 4,
      'activityCompleted': 3,
      'delivrableTotal': 4,
      'delivrableCompleted': 2,
      'taskTotal': 1,
      'task': 3,
      'alertLevel': 0,
      'hustle': 1
    },
    {
      'date': "2024-08-29",
      'capacityLevelMax': 10,
      'capacityLevel': 8,
      'workLoadLevel': 6,
      'completedLevel': 4,
      'myWorkLoadLevel': 0,
      'myCompletedLevel': 0,
      'activityTotal': 4,
      'activityCompleted': 3,
      'delivrableTotal': 4,
      'delivrableCompleted': 2,
      'taskTotal': 1,
      'task': 3,
      'alertLevel': 0,
      'hustle': 1
    },
    {
      'date': "2024-08-30",
      'capacityLevelMax': 10,
      'capacityLevel': 8,
      'workLoadLevel': 6,
      'completedLevel': 4,
      'myWorkLoadLevel': 0,
      'myCompletedLevel': 0,
      'activityTotal': 4,
      'activityCompleted': 3,
      'delivrableTotal': 4,
      'delivrableCompleted': 2,
      'taskTotal': 1,
      'task': 3,
      'alertLevel': 0,
      'hustle': 1
    },
    {
      'date': "2024-09-01",
      'capacityLevelMax': 10,
      'capacityLevel': 8,
      'workLoadLevel': 6,
      'completedLevel': 4,
      'myWorkLoadLevel': 0,
      'myCompletedLevel': 0,
      'activityTotal': 4,
      'activityCompleted': 3,
      'delivrableTotal': 4,
      'delivrableCompleted': 2,
      'taskTotal': 1,
      'task': 3,
      'alertLevel': 0,
      'hustle': 1
    },
    {
      'date': "2024-09-02",
      'capacityLevelMax': 10,
      'capacityLevel': 8,
      'workLoadLevel': 6,
      'completedLevel': 4,
      'myWorkLoadLevel': 0,
      'myCompletedLevel': 0,
      'activityTotal': 4,
      'activityCompleted': 3,
      'delivrableTotal': 4,
      'delivrableCompleted': 2,
      'taskTotal': 1,
      'task': 3,
      'alertLevel': 1,
      'hustle': 1
    },
    {
      'date': "2024-09-03",
      'capacityLevelMax': 10,
      'capacityLevel': 8,
      'workLoadLevel': 6,
      'completedLevel': 4,
      'myWorkLoadLevel': 0,
      'myCompletedLevel': 0,
      'activityTotal': 4,
      'activityCompleted': 3,
      'delivrableTotal': 4,
      'delivrableCompleted': 2,
      'taskTotal': 1,
      'task': 3,
      'alertLevel': 0,
      'hustle': 1
    },
    {
      'date': "2024-09-04",
      'capacityLevelMax': 10,
      'capacityLevel': 8,
      'workLoadLevel': 6,
      'completedLevel': 4,
      'myWorkLoadLevel': 0,
      'myCompletedLevel': 0,
      'activityTotal': 4,
      'activityCompleted': 3,
      'delivrableTotal': 4,
      'delivrableCompleted': 2,
      'taskTotal': 1,
      'task': 3,
      'alertLevel': 2,
      'hustle': 1
    },
    {
      'date': "2024-09-05",
      'capacityLevelMax': 10,
      'capacityLevel': 8,
      'workLoadLevel': 6,
      'completedLevel': 4,
      'myWorkLoadLevel': 0,
      'myCompletedLevel': 0,
      'activityTotal': 4,
      'activityCompleted': 3,
      'delivrableTotal': 4,
      'delivrableCompleted': 2,
      'taskTotal': 1,
      'task': 3,
      'alertLevel': 0,
      'hustle': 1
    },
    {
      'date': "2024-09-06",
      'capacityLevelMax': 0,
      'capacityLevel': 0,
      'workLoadLevel': 0,
      'completedLevel': 0,
      'myWorkLoadLevel': 0,
      'myCompletedLevel': 0,
      'activityTotal': 0,
      'activityCompleted': 0,
      'delivrableTotal': 0,
      'delivrableCompleted': 0,
      'taskTotal': 0,
      'task': 0,
      'alertLevel': 0,
      'hustle': 1
    },
    {
      'date': "2024-09-07",
      'capacityLevelMax': 10,
      'capacityLevel': 8,
      'workLoadLevel': 6,
      'completedLevel': 4,
      'myWorkLoadLevel': 0,
      'myCompletedLevel': 0,
      'activityTotal': 4,
      'activityCompleted': 3,
      'delivrableTotal': 4,
      'delivrableCompleted': 2,
      'taskTotal': 1,
      'task': 3,
      'alertLevel': 0,
      'hustle': 1
    },
    {
      'date': "2024-09-08",
      'capacityLevelMax': 10,
      'capacityLevel': 8,
      'workLoadLevel': 6,
      'completedLevel': 4,
      'myWorkLoadLevel': 0,
      'myCompletedLevel': 0,
      'activityTotal': 4,
      'activityCompleted': 3,
      'delivrableTotal': 4,
      'delivrableCompleted': 2,
      'taskTotal': 1,
      'task': 3,
      'alertLevel': 0,
      'hustle': 1
    },
    {
      'date': "2024-09-09",
      'capacityLevelMax': 10,
      'capacityLevel': 8,
      'workLoadLevel': 6,
      'completedLevel': 4,
      'myWorkLoadLevel': 0,
      'myCompletedLevel': 0,
      'activityTotal': 4,
      'activityCompleted': 3,
      'delivrableTotal': 4,
      'delivrableCompleted': 2,
      'taskTotal': 1,
      'task': 3,
      'alertLevel': 0,
      'hustle': 1
    },
    {
      'date': "2024-09-10",
      'capacityLevelMax': 10,
      'capacityLevel': 8,
      'workLoadLevel': 6,
      'completedLevel': 4,
      'myWorkLoadLevel': 0,
      'myCompletedLevel': 0,
      'activityTotal': 4,
      'activityCompleted': 3,
      'delivrableTotal': 4,
      'delivrableCompleted': 2,
      'taskTotal': 1,
      'task': 3,
      'alertLevel': 2,
      'hustle': 1
    },
    {
      'date': "2024-09-11",
      'capacityLevelMax': 10,
      'capacityLevel': 8,
      'workLoadLevel': 6,
      'completedLevel': 4,
      'myWorkLoadLevel': 0,
      'myCompletedLevel': 0,
      'activityTotal': 4,
      'activityCompleted': 3,
      'delivrableTotal': 4,
      'delivrableCompleted': 2,
      'taskTotal': 1,
      'task': 3,
      'alertLevel': 0,
      'hustle': 1
    },
    {
      'date': "2024-09-12",
      'capacityLevelMax': 10,
      'capacityLevel': 8,
      'workLoadLevel': 6,
      'completedLevel': 4,
      'myWorkLoadLevel': 0,
      'myCompletedLevel': 0,
      'activityTotal': 4,
      'activityCompleted': 3,
      'delivrableTotal': 4,
      'delivrableCompleted': 2,
      'taskTotal': 1,
      'task': 3,
      'alertLevel': 0,
      'hustle': 1
    },
    {
      'date': "2024-09-13",
      'capacityLevelMax': 10,
      'capacityLevel': 8,
      'workLoadLevel': 6,
      'completedLevel': 4,
      'myWorkLoadLevel': 0,
      'myCompletedLevel': 0,
      'activityTotal': 4,
      'activityCompleted': 3,
      'delivrableTotal': 4,
      'delivrableCompleted': 2,
      'taskTotal': 1,
      'task': 3,
      'alertLevel': 0,
      'hustle': 1
    },
    {
      'date': "2024-09-14",
      'capacityLevelMax': 10,
      'capacityLevel': 8,
      'workLoadLevel': 6,
      'completedLevel': 4,
      'myWorkLoadLevel': 0,
      'myCompletedLevel': 0,
      'activityTotal': 4,
      'activityCompleted': 3,
      'delivrableTotal': 4,
      'delivrableCompleted': 2,
      'taskTotal': 1,
      'task': 3,
      'alertLevel': 0,
      'hustle': 1
    },
    {
      'date': "2024-09-15",
      'capacityLevelMax': 10,
      'capacityLevel': 8,
      'workLoadLevel': 6,
      'completedLevel': 4,
      'myWorkLoadLevel': 0,
      'myCompletedLevel': 0,
      'activityTotal': 4,
      'activityCompleted': 3,
      'delivrableTotal': 4,
      'delivrableCompleted': 2,
      'taskTotal': 1,
      'task': 3,
      'alertLevel': 0,
      'hustle': 1
    },
    {
      'date': "2024-09-16",
      'capacityLevelMax': 10,
      'capacityLevel': 8,
      'workLoadLevel': 6,
      'completedLevel': 4,
      'myWorkLoadLevel': 0,
      'myCompletedLevel': 0,
      'activityTotal': 4,
      'activityCompleted': 3,
      'delivrableTotal': 4,
      'delivrableCompleted': 2,
      'taskTotal': 1,
      'task': 3,
      'alertLevel': 0,
      'hustle': 1
    },
    {
      'date': "2024-09-17",
      'capacityLevelMax': 10,
      'capacityLevel': 8,
      'workLoadLevel': 6,
      'completedLevel': 4,
      'myWorkLoadLevel': 0,
      'myCompletedLevel': 0,
      'activityTotal': 4,
      'activityCompleted': 3,
      'delivrableTotal': 4,
      'delivrableCompleted': 2,
      'taskTotal': 1,
      'task': 3,
      'alertLevel': 0,
      'hustle': 1
    },
    {
      'date': "2024-09-18",
      'capacityLevelMax': 10,
      'capacityLevel': 8,
      'workLoadLevel': 6,
      'completedLevel': 4,
      'myWorkLoadLevel': 0,
      'myCompletedLevel': 0,
      'activityTotal': 4,
      'activityCompleted': 3,
      'delivrableTotal': 4,
      'delivrableCompleted': 2,
      'taskTotal': 1,
      'task': 3,
      'alertLevel': 0,
      'hustle': 1
    },
    {
      'date': "2024-09-19",
      'capacityLevelMax': 10,
      'capacityLevel': 8,
      'workLoadLevel': 6,
      'completedLevel': 4,
      'myWorkLoadLevel': 0,
      'myCompletedLevel': 0,
      'activityTotal': 4,
      'activityCompleted': 3,
      'delivrableTotal': 4,
      'delivrableCompleted': 2,
      'taskTotal': 1,
      'task': 3,
      'alertLevel': 0,
      'hustle': 1
    },
    {
      'date': "2024-09-20",
      'capacityLevelMax': 10,
      'capacityLevel': 8,
      'workLoadLevel': 6,
      'completedLevel': 4,
      'myWorkLoadLevel': 0,
      'myCompletedLevel': 0,
      'activityTotal': 4,
      'activityCompleted': 3,
      'delivrableTotal': 4,
      'delivrableCompleted': 2,
      'taskTotal': 1,
      'task': 3,
      'alertLevel': 0,
      'hustle': 1
    },
    {
      'date': "2024-09-21",
      'capacityLevelMax': 10,
      'capacityLevel': 8,
      'workLoadLevel': 6,
      'completedLevel': 4,
      'myWorkLoadLevel': 0,
      'myCompletedLevel': 0,
      'activityTotal': 4,
      'activityCompleted': 3,
      'delivrableTotal': 4,
      'delivrableCompleted': 2,
      'taskTotal': 1,
      'task': 3,
      'alertLevel': 0,
      'hustle': 1
    },
    {
      'date': "2024-09-22",
      'capacityLevelMax': 10,
      'capacityLevel': 8,
      'workLoadLevel': 6,
      'completedLevel': 4,
      'myWorkLoadLevel': 0,
      'myCompletedLevel': 0,
      'activityTotal': 4,
      'activityCompleted': 3,
      'delivrableTotal': 4,
      'delivrableCompleted': 2,
      'taskTotal': 1,
      'task': 3,
      'alertLevel': 0,
      'hustle': 1
    },
    {
      'date': "2024-09-23",
      'capacityLevelMax': 10,
      'capacityLevel': 8,
      'workLoadLevel': 6,
      'completedLevel': 4,
      'myWorkLoadLevel': 0,
      'myCompletedLevel': 0,
      'activityTotal': 4,
      'activityCompleted': 3,
      'delivrableTotal': 4,
      'delivrableCompleted': 2,
      'taskTotal': 1,
      'task': 3,
      'alertLevel': 0,
      'hustle': 1
    },
    {
      'date': "2024-09-24",
      'capacityLevelMax': 10,
      'capacityLevel': 8,
      'workLoadLevel': 6,
      'completedLevel': 4,
      'myWorkLoadLevel': 0,
      'myCompletedLevel': 0,
      'activityTotal': 4,
      'activityCompleted': 3,
      'delivrableTotal': 4,
      'delivrableCompleted': 2,
      'taskTotal': 1,
      'task': 3,
      'alertLevel': 0,
      'hustle': 1
    },
    {
      'date': "2024-09-25",
      'capacityLevelMax': 10,
      'capacityLevel': 8,
      'workLoadLevel': 6,
      'completedLevel': 4,
      'myWorkLoadLevel': 0,
      'myCompletedLevel': 0,
      'activityTotal': 4,
      'activityCompleted': 3,
      'delivrableTotal': 4,
      'delivrableCompleted': 2,
      'taskTotal': 1,
      'task': 3,
      'alertLevel': 0,
      'hustle': 1
    },
    {
      'date': "2024-09-26",
      'capacityLevelMax': 10,
      'capacityLevel': 8,
      'workLoadLevel': 6,
      'completedLevel': 4,
      'myWorkLoadLevel': 0,
      'myCompletedLevel': 0,
      'activityTotal': 4,
      'activityCompleted': 3,
      'delivrableTotal': 4,
      'delivrableCompleted': 2,
      'taskTotal': 1,
      'task': 3,
      'alertLevel': 0,
      'hustle': 1
    },
    {
      'date': "2024-09-27",
      'capacityLevelMax': 10,
      'capacityLevel': 8,
      'workLoadLevel': 6,
      'completedLevel': 4,
      'myWorkLoadLevel': 0,
      'myCompletedLevel': 0,
      'activityTotal': 4,
      'activityCompleted': 3,
      'delivrableTotal': 4,
      'delivrableCompleted': 2,
      'taskTotal': 1,
      'task': 3,
      'alertLevel': 0,
      'hustle': 1
    },
    {
      'date': "2024-09-28",
      'capacityLevelMax': 10,
      'capacityLevel': 8,
      'workLoadLevel': 6,
      'completedLevel': 4,
      'myWorkLoadLevel': 0,
      'myCompletedLevel': 0,
      'activityTotal': 4,
      'activityCompleted': 3,
      'delivrableTotal': 4,
      'delivrableCompleted': 2,
      'taskTotal': 1,
      'task': 3,
      'alertLevel': 0,
      'hustle': 1
    },
    {
      'date': "2024-09-29",
      'capacityLevelMax': 10,
      'capacityLevel': 8,
      'workLoadLevel': 6,
      'completedLevel': 4,
      'myWorkLoadLevel': 0,
      'myCompletedLevel': 0,
      'activityTotal': 4,
      'activityCompleted': 3,
      'delivrableTotal': 4,
      'delivrableCompleted': 2,
      'taskTotal': 1,
      'task': 3,
      'alertLevel': 0,
      'hustle': 1
    },
    {
      'date': "2024-09-30",
      'capacityLevelMax': 10,
      'capacityLevel': 8,
      'workLoadLevel': 6,
      'completedLevel': 4,
      'myWorkLoadLevel': 0,
      'myCompletedLevel': 0,
      'activityTotal': 4,
      'activityCompleted': 3,
      'delivrableTotal': 4,
      'delivrableCompleted': 2,
      'taskTotal': 1,
      'task': 3,
      'alertLevel': 1,
      'hustle': 1
    },
    {
      'date': "2024-10-18",
      'capacityLevelMax': 10,
      'capacityLevel': 8,
      'workLoadLevel': 6,
      'completedLevel': 4,
      'myWorkLoadLevel': 0,
      'myCompletedLevel': 0,
      'activityTotal': 4,
      'activityCompleted': 3,
      'delivrableTotal': 4,
      'delivrableCompleted': 2,
      'taskTotal': 1,
      'task': 3,
      'alertLevel': 1,
      'hustle': 1
    },
  ];

  final List<dynamic> stages = [
    {
      'prs_id': '5659-446-54545',
      'type': 'other',
      'name': 'Swiip : Conception',
      'startDate': "2024-08-03",
      'endDate': "2024-08-08",
      'totalActivity': 5,
      'totalActivityFinished': 5,
      'totalDelivrable': 5,
      'totalDelivrableFinished': 5,
      'totalTask': 5,
      'totalTaskFinished': 5,
      'progress': 100,
      'releaseLabel': '1.87',
      'releaseProgress': 24,
    },
    {
      'prs_id': '5659-446-54545',
      'type': 'milestone',
      'name': 'Floralis : Ateliers UX',
      'startDate': "2024-08-05",
      'endDate': "2024-08-09",
      'totalActivity': 5,
      'totalActivityFinished': 5,
      'totalDelivrable': 5,
      'totalDelivrableFinished': 4,
      'totalTask': 5,
      'totalTaskFinished': 2,
      'progress': 80,
      'releaseLabel': '1.87',
      'releaseProgress': 24,
    },
    {
      'prs_id': '5659-446-54545',
      'type': 'milestone',
      'name': 'Floralis : Ateliers UX 2',
      'startDate': "2024-08-10",
      'endDate': "2024-08-18",
      'totalActivity': 5,
      'totalActivityFinished': 1,
      'totalDelivrable': 5,
      'totalDelivrableFinished': 3,
      'totalTask': 5,
      'totalTaskFinished': 0,
      'progress': 40,
      'releaseLabel': '1.87',
      'releaseProgress': 24,
    },
    {
      'prs_id': '5659-446-54545',
      'type': 'milestone',
      'name': 'Floralis : Développement authentification',
      'startDate': "2024-08-21",
      'endDate': "2024-08-27",
      'totalActivity': 5,
      'totalActivityFinished': 0,
      'totalDelivrable': 5,
      'totalDelivrableFinished': 0,
      'totalTask': 5,
      'totalTaskFinished': 0,
      'progress': 0,
      'releaseLabel': '1.88',
      'releaseProgress': 0,
    },
    {
      'prs_id': '5659-446-54545',
      'type': 'milestone',
      'name': 'Floralis : Intégration graphique',
      'startDate': "2024-08-23",
      'endDate': "2024-08-25",
      'totalActivity': 5,
      'totalActivityFinished': 0,
      'totalDelivrable': 5,
      'totalDelivrableFinished': 0,
      'totalTask': 5,
      'totalTaskFinished': 0,
      'progress': 0,
      'releaseLabel': '1.88',
      'releaseProgress': 0,
    },
    {
      'prs_id': '5659-446-54545',
      'type': 'milestone',
      'name': 'Floralis : Intégration graphique 2',
      'startDate': "2024-08-24",
      'endDate': "2024-08-30",
      'totalActivity': 5,
      'totalActivityFinished': 0,
      'totalDelivrable': 5,
      'totalDelivrableFinished': 0,
      'totalTask': 5,
      'totalTaskFinished': 0,
      'progress': 0,
      'releaseLabel': '1.89',
      'releaseProgress': 0,
    },
  ];

  final Map<String, Color> colors = {
    'primary': const Color(0xFFCE49AF),
    'secondary': const Color(0xFFFFC500),
    'primaryText': const Color(0xFFE1E1E1),
    'primaryBackground': const Color(0xFF111A30),
    'accent1': const Color(0xFF818497),
    'accent2': const Color(0xFF5C5E71),
    'error': const Color(0xFFFF5963),
    'warning': const Color(0xFFF9CF58)
  };

  void openDayDetail(String date, String? prjId, int? dayProgress) {}

  void openAddStage(String? prsId) {}

  const double width = 300;
  const double height = 480;

  test(
      'Vérifie si le widget se charge',
      () => {
            TimelineXp(
                width: width,
                height: height,
                colors: colors,
                elements: elements,
                stages: stages,
                project: project,
                openDayDetail: openDayDetail,
                openAddStage: openAddStage)
          });
}
